In [2]:
import seaborn as sns

#Loading the dataset
iris=sns.load_dataset("iris")

In [3]:
iris.to_csv("iris.csv",index=False)

In [4]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [7]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
iris.shape

(150, 5)

In [10]:
iris['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [11]:
iris['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

## Encoding the species

### One Hot Enocoding

In [12]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [13]:
encoder=OneHotEncoder()

In [14]:
encoded=encoder.fit_transform(iris[['species']])

In [15]:
encoded

<150x3 sparse matrix of type '<class 'numpy.float64'>'
	with 150 stored elements in Compressed Sparse Row format>

In [16]:
encoded_iris=pd.DataFrame(encoded.toarray(),columns=encoder.get_feature_names_out())

In [17]:
encoded_iris

species_setosa  species_versicolor  species_virginica
0               1.0                 0.0                0.0
1               1.0                 0.0                0.0
2               1.0                 0.0                0.0
3               1.0                 0.0                0.0
4               1.0                 0.0                0.0
..              ...                 ...                ...
145             0.0                 0.0                1.0
146             0.0                 0.0                1.0
147             0.0                 0.0                1.0
148             0.0                 0.0                1.0
149             0.0                 0.0                1.0

[150 rows x 3 columns]

### Label Encoding

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
label_encoder=LabelEncoder()

In [22]:
iris['species']=label_encoder.fit_transform(iris['species'])

In [23]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [24]:
iris

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [25]:
iris['species'].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [26]:
X=iris.drop(columns=['species'])
y=iris['species']

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [30]:
from sklearn.linear_model import LogisticRegression
logistic_model=LogisticRegression(solver='lbfgs')

In [31]:
logistic_model.fit(X_train,y_train)

LogisticRegression()

In [32]:
y_pred=logistic_model.predict(X_test)

In [33]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(y_pred,y_test))


[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [35]:
print(accuracy_score(y_pred,y_test))

1.0


In [36]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



### Predictions for new data

In [43]:
import numpy as np
new_data=np.array([[5.1,3.5,1.4,0.2]])

In [45]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [48]:
sepal_length=5.1
sepal_width=3.5
petal_length=1.4
petal_width=0.2

In [49]:
to_predict=np.array([[sepal_length,sepal_width,petal_length,petal_width]])

In [50]:
to_predict_df=pd.DataFrame(to_predict,columns=X.columns)

In [51]:
predictions=logistic_model.predict(to_predict_df)

In [52]:
predictions

array([0], dtype=int64)

In [53]:
species_predictions=label_encoder.inverse_transform(predictions)

In [54]:
species_predictions

array([0])

In [55]:
for i, prediction in enumerate(species_predictions):
    print(f"Sample {i+1}; Predicted species is {prediction}")

Sample 1; Predicted species is 0
